### PR TITLE
Num zones off by1 for get_all_areas

### PR DESCRIPTION
**Pull request by CharlyAndersonUK**
Hi David.

I'm using an Premire Elite 64, and noticed that there appears to be an end loop off-by-one in  get_all_areas.
It showed itself on my system due to not getting all the areas (I have 4 out of 4 areas in use)

regards
Charly

### CODE REVIEW

**Comment by mpredfearn** [comment]
Can you squash these commits?

**Comment by CharlyAndersonUK** [comment]
Hi

Yes. I was going to do another pull request, as I now have other mods I'd
like to do consider:

   1. Added arm/disarm areas using mqtt.
   2. Closed status update window, where the state of zones or areas could
   be incorrect if either the server is started after the panel is armed or if
   an event is missed (eg. network glitch).
   3. Updated to Python 3.8. This entailed quite significant updates due to
   breaking changes in Python.
   4. Add further texecom API call support
   5. various other updates

I'll now had this running for a couple of weeks OK, so I will raise a new
pull request in the next few days.

Thanks for getting back to me.

Regards
Charly

**Comment by mpredfearn** [comment]
Cool! Those updates sound great (I had a crack at a couple of them but didn't get too far).

**Comment by CharlyAndersonUK** [comment]
WIll raise a replacement pull request, to include other updates.

**Pull request closed without merging**
